substitutions:
  name: "fd25"
  dallas_pin: '19'
  dallas_address_heat_exchanger_temp: '0xa4b32d851e64ff28'
  dallas_address_outdoor_temp:        '0x00ca55851e64ff28'

esp32:
  variant: ESP32
  framework:
    type: esp-idf


esphome:
  compile_process_limit: 2

packages:
  - !include z-basics.yaml

wifi:
  use_address: 10.0.0.231

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome
    refresh: 0s
 # - source:
 #     type: git
 #     url: https://github.com/MarkoPaasila/esphome-snippets
 #     ref: hp-ukf
 #   components: [ hp_ukf ]
 #   refresh: 0s
  - source:
      type: local
      path: components
    components: [ hp_ukf ]
    refresh: 0s

hp_ukf:
  id: ukf
  update_interval: 5s
  climate: hp
  inlet_temperature: tin
  inlet_humidity: hin
  outlet_temperature: tout
  outlet_humidity: hout
  air_flow: vol
  compressor_frequency: compressor_freq
  power_sensor: power
  outside_temperature: outdoor_temp
  outside_coil_temperature_after: heat_exchanger_temp
  inside_room_temperature: indoor_temp
  inside_room_humidity: indoor_humidity
  # atmospheric_pressure: atmospheric_pressure
  virtual_coil: true
  track_temperature_derivatives: true
  em_autotune: true
  em_inflation: 1.0
  em_lambda_q: 0.998
  em_lambda_r_inlet: 0.998
  em_lambda_r_outlet: 0.998
  # Optional: expose tuned Q/R and lambdas as sensors (for verification/debug)
  em_q_t_out:
    name: "${name} EM Q T Out"
  em_r_t_out:
    name: "${name} EM R T Out"
  em_q_t_in:
    name: "${name} EM Q T In"
  em_r_t_in:
    name: "${name} EM R T In"
  em_q_rh_in:
    name: "${name} EM Q RH In"
  em_r_rh_in:
    name: "${name} EM R RH In"
  em_q_rh_out:
    name: "${name} EM Q RH Out"
  em_r_rh_out:
    name: "${name} EM R RH Out"
  inlet_absolute_humidity:
    name: "${name} Inlet Absolute Humidity"
  inlet_dew_point:
    name: "${name} Inlet Dew Point"
  inlet_enthalpy:
    name: "${name} Inlet Enthalpy"
  outlet_absolute_humidity:
    name: "${name} Outlet Absolute Humidity"
  outlet_dew_point:
    name: "${name} Outlet Dew Point"
  outlet_enthalpy:
    name: "${name} Outlet Enthalpy"
  filtered_air_flow:
    name: "${name} Filtered Air Flow"
  delivered_power:
    name: "${name} Delivered Power"
  filtered_virtual_coil_temperature:
    name: "${name} Virtual Coil Temperature"
  # Optional: heat pump state machine (state string + defrosting binary)
  state:
    name: "${name} HP State"
  defrosting:
    id: hp_state_defrosting
    name: "${name} Defrosting"
    on_state:
      - then:
          - component.update: vol

climate:
  - platform: cn105
    id: hp
    name: MSZ-FD25
    uart_id: HP_UART
    update_interval: 1200ms
    visual:
      min_temperature: 16.0
      max_temperature: 31.0
      temperature_step: 1.0 
    compressor_frequency_sensor:
      name: "Compressor frequency"
      id: compressor_freq
      filters: 
        - heartbeat: 300s
        - lambda: |-
            if (x <= 4.1) {          // use <= 4.1 to catch minor float noise around 4
              return 0.0;
            } else {
              return x;
            }
    on_state: 
      then:
        - component.update: vol

one_wire:
  - platform: gpio
    pin: $dallas_pin

i2c:
  - id: i2c1
    sda: 33
    scl: 32
    scan: true
    frequency: 100kHz
  - id: i2c0
    sda: 27
    scl: 26
    scan: true
    frequency: 100kHz

uart:
  - id: pzem_uart
    tx_pin: 17
    rx_pin: 16
    baud_rate: 9600
    stop_bits: 1
    debug:
  - id: HP_UART
    tx_pin: 1
    rx_pin: 3
    baud_rate: 2400

modbus:
  id: mbus
  uart_id: pzem_uart
  disable_crc: true

sensor:      
# -------------- SHT30 ------------------ #
  - platform: sht3xd
    i2c_id: i2c0
    update_interval: 5s
    temperature:
      id: tin
    humidity:
      id: hin
  - platform: sht3xd
    i2c_id: i2c1
    update_interval: 5s
    temperature:
      id: tout
    humidity:
      id: hout
  - name: "Outdoor unit heat exchanger temperature"
    platform: dallas_temp
    address: $dallas_address_heat_exchanger_temp # Remember to define this on platform.yaml
    id: heat_exchanger_temp
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
  - name: "Outdoor temperature"
    platform: dallas_temp
    address: $dallas_address_outdoor_temp # Remember to define this on platform.yaml
    id: outdoor_temp
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
  - id: indoor_temp
    name: "Indoor temperature"
    platform: homeassistant
    entity_id: sensor.bme280_1_bme280_temperature
  - id: indoor_humidity
    name: "Indoor humidity"
    platform: homeassistant
    entity_id: sensor.bme280_1_bme280_humidity
  - id: atmospheric_pressure
    name: "Atmospheric pressure"
    platform: homeassistant
    entity_id: sensor.bme280_1_bme280_pressure

  - name: "Air Volume"
    platform: template
    id: vol
    update_interval: never
    unit_of_measurement: "l/s"
    state_class: measurement
    lambda: |-
      int mode = (int) id(hp).mode;
      auto fan_opt = id(hp).fan_mode;
      int s = fan_opt.has_value() ? (int) fan_opt.value() : 0;
      bool heat = (mode == 1 || mode == 3);
      bool cool = (mode == 2 || mode == 4);
      bool off = (mode == 0);
      bool defrosting = id(hp_state_defrosting).state;

      if (cool) {
        if (s == 3){return 76.67;}
        else if (s == 4) {return 111.67;}
        else if (s == 6) {return 153.33;}
        else if (s == 5) {return 201.67;}
        else {return 76.67;}
      } else if (heat) {
        if (defrosting){return 2.78;}
        else if (s == 3) {return 75.0;}
        else if (s == 4) {return 111.67;}
        else if (s == 6) {return 153.33;}
        else if (s == 5) {return 201.67;}
        else {return 13.89;}
      }
      return 0.0;

# ----------------- PZEM ------------------ #
  - platform: pzemac
    update_interval: 5s
    modbus_id: mbus
    power:
      name: "Power"
      id: power
      unit_of_measurement: "W"
      icon: mdi:flash-outline
      device_class: power
      state_class: measurement

debug:
  update_interval: 10s

logger:
  # hardware_uart: UART1 # Uncomment on ESP8266 devices
  # Global level controls what is compiled in; INFO or DEBUG needed for hp_ukf Q/R logs
  level: DEBUG
  logs:
    hp_ukf: DEBUG
    EVT_SETS: ERROR
    WIFI: ERROR
    MQTT: ERROR
    WRITE_SETTINGS: ERROR
    SETTINGS: ERROR
    STATUS: ERROR
    # CN105 connection/bootstrap diagnostics (UART init + CONNECT handshake)
    CN105_CONN: ERROR
    CN105Climate: WARN
    CN105: ERROR
    climate: WARN
    sensor: WARN
    chkSum: ERROR
    WRITE: WARN
    READ: WARN
    Header: ERROR
    Decoder: ERROR
    CONTROL_WANTED_SETTINGS: ERROR