# Example ESPHome configuration using the hp_ukf external component.
# Use this component from a device YAML by adding the external_components
# block and an hp_ukf: section.
#
# In your device YAML (e.g. node.yaml in the same folder as components/):
#
# external_components:
#   - source:
#       type: local
#       path: components
#     components: [ hp_ukf ]
#
# hp_ukf:
#   id: my_hp_ukf
#   update_interval: 60s

substitutions:
  name: hp-ukf-example


# Load the hp_ukf external component from the local components folder
external_components:
  - source:
      type: local
      path: components
    components: [ hp_ukf ]

# HP-UKF component instance
hp_ukf:
  id: hp_ukf
  name: ${name}_hp_ukf
  update_interval: 60s
