# Example ESPHome configuration using the hp_ukf external component.
# Wire inlet/outlet temperature and humidity sensors to hp_ukf; the component
# runs a time-discrete UKF and exposes filtered state and optional derivatives.
#
# Replace the template sensors below with your real sensors (e.g. DHT, HTU21D)
# for inlet and outlet air.

substitutions:
  name: hp-ukf-example

# Load the hp_ukf external component from the local components folder
external_components:
  - source:
      type: local
      path: components
    components: [ hp_ukf ]

# Example input sensors (replace with your hardware sensors, e.g. DHT/HTU21D)
sensor:
  - platform: template
    id: inlet_temperature
    name: "${name} Inlet Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    update_interval: 1s
    lambda: |-
      return 20.0f;
  - platform: template
    id: inlet_humidity
    name: "${name} Inlet Humidity"
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 1s
    lambda: |-
      return 50.0f;
  - platform: template
    id: outlet_temperature
    name: "${name} Outlet Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    update_interval: 1s
    lambda: |-
      return 22.0f;
  - platform: template
    id: outlet_humidity
    name: "${name} Outlet Humidity"
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 1s
    lambda: |-
      return 45.0f;
  # Optional: air flow in L/s (liters per second). When set, UKF also tracks
  # air flow and delivers filtered_air_flow and delivered_power (kW).
  - platform: template
    id: air_flow
    name: "${name} Air Flow"
    unit_of_measurement: "L/s"
    state_class: measurement
    accuracy_decimals: 2
    update_interval: 1s
    lambda: |-
      return 100.0f;

# HP-UKF component: user provides the four sensors; UKF runs at update_interval.
# Optional: air_flow (L/s) adds air flow and delivered power to UKF state.
# Optional: climate + compressor_frequency (e.g. Mitsubishi CN105) use action and
# compressor Hz as control inputs so delivered_power is forced to 0 when OFF/IDLE.
# Optional: EM auto-tune adapts process (Q) and measurement (R) noise with
# separate forgetting factors for inlet (slower) vs outlet (faster dynamics).
hp_ukf:
  id: hp_ukf
  update_interval: 1s
  inlet_temperature: inlet_temperature
  inlet_humidity: inlet_humidity
  outlet_temperature: outlet_temperature
  outlet_humidity: outlet_humidity
  # Optional: air flow sensor in L/s; enables filtered_air_flow and delivered_power
  air_flow: air_flow
  # Optional: with MitsubishiCN105ESPHome, reference climate, compressor sensor, and power sensor
  # (give compressor_frequency_sensor and input_power_sensor ids in the climate block)
  # climate: hp
  # compressor_frequency: compressor_freq
  # power_sensor: hp_power   # input power in W; correlated to compressor speed
  # Optional: environment/room control inputs (passed to UKF; stored for process model use)
  # outside_temperature: outdoor_temp
  # outside_coil_temperature_before: pipe_before_coil
  # outside_coil_temperature_after: pipe_after_coil
  # inside_room_temperature: room_temp
  # inside_room_humidity: room_humidity
  filtered_air_flow:
    name: "${name} Filtered Air Flow"
  delivered_power:
    name: "${name} Delivered Power"
  track_temperature_derivatives: true
  em_autotune: true
  em_lambda_q: 0.995
  em_lambda_r_inlet: 0.998
  em_lambda_r_outlet: 0.98
  # em_inflation: 0.5  # default: EM estimates scaled by 1.5 before smoothing (R/Q 50% larger)
  # Optional: expose tuned Q/R and lambdas as sensors (for verification/debug)
  em_q_t_out:
    name: "${name} EM Q T Out"
  em_r_t_out:
    name: "${name} EM R T Out"

# The component exposes: Filtered Inlet/Outlet Temperature and Humidity,
# and (if track_temperature_derivatives is true) Filtered Inlet/Outlet
# Temperature Derivative (°C/s) and Filtered Inlet/Outlet Humidity Derivative (%/s).
# With air_flow set: Filtered Air Flow (L/s) and Delivered Power (kW).
# With em_autotune, optional sensors for Q/R diagonals and lambdas can be added.
